// Dados: filmes dos Beatles (8 itens, 9 campos cada)

import filmsImg from '../assets/image copy 2.png'
import daysNightImg from '../assets/image copy 3.png'
import homeImg from '../assets/image copy 4.png'

export const films = [
  {
    id: 1,
    title: "A Hard Day's Night",
    year: '1964',
    categoria: 'Filme',
    descricao: 'Primeiro longa-metragem dos Beatles. Captura o estilo documental e o humor da banda.',
    status: 'Disponível',
    imagem: daysNightImg,
    diretor: 'Richard Lester',
    duracao: '87 min',
    slug: 'a-hard-days-night',
  },
  {
    id: 2,
    title: 'Help!',
    year: '1965',
    categoria: 'Filme',
    descricao: 'Segundo filme, agora em cores e com uma aventura que mistura a banda com um culto bizarro.',
    status: 'Disponível',
    imagem: filmsImg,
    diretor: 'Richard Lester',
    duracao: '92 min',
    slug: 'help',
  },
  {
    id: 3,
    title: 'Magical Mystery Tour',
    year: '1967',
    categoria: 'Filme',
    descricao: 'Filme experimental para a televisão britânica. Recebeu críticas hostis na estreia.',
    status: 'Disponível',
    imagem: filmsImg,
    diretor: 'The Beatles',
    duracao: '55 min',
    slug: 'magical-mystery-tour',
  },
  {
    id: 4,
    title: 'Yellow Submarine',
    year: '1968',
    categoria: 'Animação',
    descricao: 'Filme de animação psicodélica. Os próprios Beatles só aparecem nos últimos minutos.',
    status: 'Disponível',
    imagem: filmsImg,
    diretor: 'George Dunning',
    duracao: '85 min',
    slug: 'yellow-submarine',
  },
  {
    id: 5,
    title: 'Let It Be',
    year: '1970',
    categoria: 'Documentário',
    descricao: 'Documenta as sessões de gravação do último álbum dos Beatles. Lançado pouco após a separação.',
    status: 'Indisponível',
    imagem: filmsImg,
    diretor: 'Michael Lindsay-Hogg',
    duracao: '80 min',
    slug: 'let-it-be',
  },
  {
    id: 6,
    title: 'The Beatles at Shea Stadium',
    year: '1966',
    categoria: 'Documentário',
    descricao: 'Registro do concerto histórico no Shea Stadium para 55.600 pessoas.',
    status: 'Disponível',
    imagem: filmsImg,
    diretor: 'Bob Precht',
    duracao: '50 min',
    slug: 'shea-stadium',
  },
  {
    id: 7,
    title: 'Get Back',
    year: '2021',
    categoria: 'Documentário',
    descricao: 'Documentário de Peter Jackson com 60 horas de filmagens restauradas das sessões de Let It Be.',
    status: 'Disponível',
    imagem: homeImg,
    diretor: 'Peter Jackson',
    duracao: '468 min',
    slug: 'get-back',
  },
  {
    id: 8,
    title: 'Eight Days a Week',
    year: '2016',
    categoria: 'Documentário',
    descricao: 'Ron Howard dirige o documentário sobre a fase de shows ao vivo dos Beatles (1962-1966).',
    status: 'Disponível',
    imagem: filmsImg,
    diretor: 'Ron Howard',
    duracao: '106 min',
    slug: 'eight-days-a-week',
  },
]