// Dados: vídeos musicais dos Beatles (8 itens, 9 campos cada)

import musicVideosImg from '../assets/image copy.png'
import comesSunImg from '../assets/image copy 2.png'
import handImg from '../assets/image copy 3.png'

export const musicVideos = [
  {
    id: 1,
    title: 'I Want To Hold Your Hand',
    year: '1964',
    categoria: 'Apresentação TV',
    descricao: 'Performance ao vivo no The Ed Sullivan Show. Apresentou os Beatles para a América.',
    status: 'Disponível',
    imagem: handImg,
    diretor: 'Ed Sullivan Productions',
    videoId: 'jenWdylTtzs',
    slug: 'i-want-hold-your-hand',
  },
  {
    id: 2,
    title: 'Here Comes the Sun',
    year: '2019',
    categoria: 'Lyric Video',
    descricao: 'Vídeo com a letra sincronizada, parte do relançamento do catálogo.',
    status: 'Disponível',
    imagem: comesSunImg,
    diretor: 'Apple Corps',
    videoId: 'K3Q9yFsmbJA',
    slug: 'here-comes-the-sun',
  },
  {
    id: 3,
    title: 'Come Together',
    year: '2018',
    categoria: 'Lyric Video',
    descricao: 'Animação psicodélica sincronizada com a faixa clássica de Abbey Road.',
    status: 'Disponível',
    imagem: musicVideosImg,
    diretor: 'Apple Corps',
    videoId: 'F2m1V4JQsCM',
    slug: 'come-together',
  },
  {
    id: 4,
    title: 'Something',
    year: '2018',
    categoria: 'Lyric Video',
    descricao: 'Vídeo animado com a clássica composição de George Harrison.',
    status: 'Disponível',
    imagem: comesSunImg,
    diretor: 'Apple Corps',
    videoId: 'F2m1V4JQsCM',
    slug: 'something',
  },
  {
    id: 5,
    title: 'Hey Jude',
    year: '1968',
    categoria: 'Promocional',
    descricao: 'Performance do single de 1968 filmada para TV britânica.',
    status: 'Disponível',
    imagem: musicVideosImg,
    diretor: 'Michael Lindsay-Hogg',
    videoId: 'A_MjCqQiLBA',
    slug: 'hey-jude',
  },
  {
    id: 6,
    title: 'Let It Be',
    year: '1970',
    categoria: 'Documentário',
    descricao: 'Clipe com trechos do documentário Let It Be de Michael Lindsay-Hogg.',
    status: 'Disponível',
    imagem: musicVideosImg,
    diretor: 'Michael Lindsay-Hogg',
    videoId: '2xDzVZ2KgIw',
    slug: 'let-it-be',
  },
  {
    id: 7,
    title: 'Yesterday',
    year: '1965',
    categoria: 'Promocional',
    descricao: 'Performance em TV da música mais regravada da história.',
    status: 'Disponível',
    imagem: musicVideosImg,
    diretor: 'Ed Sullivan Productions',
    videoId: 'NrgmdNvS7WI',
    slug: 'yesterday',
  },
  {
    id: 8,
    title: 'Blackbird',
    year: '2018',
    categoria: 'Lyric Video',
    descricao: 'Animação delicada que acompanha o solo acústico de Paul McCartney.',
    status: 'Indisponível',
    imagem: musicVideosImg,
    diretor: 'Apple Corps',
    videoId: 'Man4Xw8jt1M',
    slug: 'blackbird',
  },
]