// Dados: notícias (8 itens, 9 campos cada)

import newsImg from '../assets/image copy 5.png'
import savileRowImg from '../assets/image copy 6.png'
import bookImg from '../assets/image copy 7.png'

export const news = [
  {
    id: 1,
    title: 'Os Beatles voltam a Savile Row!',
    date: '11 de maio de 2026',
    slug: 'beatles-get-back-savile-row',
    categoria: 'Comemoração',
    excerpt: 'The Beatles at 3 Savile Row, a primeira experiência oficial para fãs, abre as portas em 2027.',
    descricao: 'Anúncio da primeira experiência oficial para fãs dos Beatles no histórico endereço de Savile Row.',
    status: 'Disponível',
    imagem: savileRowImg,
  },
  {
    id: 2,
    title: 'Livro The Beatles Anthology 2025 - Disponível',
    date: '14 de outubro de 2025',
    slug: 'beatles-anthology-book-2025-out-now',
    categoria: 'Lançamento',
    excerpt: 'The Beatles Anthology conta a história completa da banda com mais de 1300 imagens.',
    descricao: 'Lançamento do livro oficial com 1300 imagens raras dos arquivos pessoais dos Beatles.',
    status: 'Disponível',
    imagem: bookImg,
  },
  {
    id: 3,
    title: 'Revolver Super Deluxe disponível',
    date: '28 de outubro de 2022',
    slug: 'revolver-super-deluxe',
    categoria: 'Lançamento',
    excerpt: 'Edição expandida de Revolver com faixas demo e mixes alternativos.',
    descricao: 'A edição Super Deluxe do clássico de 1966 traz faixas nunca antes ouvidas e mixes alternativos.',
    status: 'Disponível',
    imagem: newsImg,
  },
  {
    id: 4,
    title: 'Get Back retorna ao Disney+',
    date: '12 de agosto de 2022',
    slug: 'get-back-disney-plus',
    categoria: 'Evento',
    excerpt: 'O documentário de Peter Jackson retorna ao Disney+ em versão restaurada.',
    descricao: 'Documentário retorna ao Disney+ com nova masterização e material extra.',
    status: 'Disponível',
    imagem: newsImg,
  },
  {
    id: 5,
    title: 'Let It Be Super Deluxe anunciado',
    date: '15 de outubro de 2021',
    slug: 'let-it-be-super-deluxe',
    categoria: 'Lançamento',
    excerpt: 'A edição Super Deluxe do álbum Let It Be chega com faixas raras.',
    descricao: 'Anúncio da edição Super Deluxe do último álbum lançado pelos Beatles em 1970.',
    status: 'Disponível',
    imagem: newsImg,
  },
  {
    id: 6,
    title: 'Dia Global dos Beatles 2026',
    date: '25 de junho de 2026',
    slug: 'global-beatles-day',
    categoria: 'Comemoração',
    excerpt: 'Celebre o Dia Global dos Beatles com a banda que mudou a história da música.',
    descricao: '25 de junho marca a primeira transmissão global de "All You Need Is Love" em 1967.',
    status: 'Disponível',
    imagem: newsImg,
  },
  {
    id: 7,
    title: 'Paul McCartney anuncia nova turnê',
    date: '02 de fevereiro de 2026',
    slug: 'paul-mccartney-tour',
    categoria: 'Evento',
    excerpt: 'Paul McCartney anuncia datas da nova turnê mundial Got Back.',
    descricao: 'Turnê mundial com datas na Europa, América do Norte e América do Sul.',
    status: 'Indisponível',
    imagem: newsImg,
  },
  {
    id: 8,
    title: 'Now and Then restaurada',
    date: '02 de novembro de 2023',
    slug: 'now-and-then',
    categoria: 'Lançamento',
    excerpt: 'A última música dos Beatles, gravada com IA para isolar a voz de John Lennon.',
    descricao: 'Lançamento de "Now and Then", considerada a última música dos Beatles.',
    status: 'Disponível',
    imagem: newsImg,
  },
]