// Dados: músicas dos Beatles (10 itens, 10 campos cada)
// Expande o array de 4 para 10 e adiciona campos extras.

import songsImg from '../assets/image copy.png'
import comesSunImg from '../assets/image copy 2.png'
import handImg from '../assets/image copy 3.png'

// songs: "Here Comes the Sun" (id 4) é reordenado para o topo (id 1) e os
// demais ids permanecem com o mesmo identificador via remapeamento abaixo.
const _songsRaw = [
  {
    rawId: 4,
    title: 'Here Comes the Sun',
    year: '1969',
    album: 'Abbey Road',
    categoria: 'Harrison',
    duracao: '3:05',
    descricao: 'George Harrison escreveu no jardim de Eric Clapton depois de um longo inverno de obrigações.',
    status: 'Disponível',
    imagem: comesSunImg,
    compositor: 'George Harrison',
    slug: 'here-comes-the-sun',
  },
  {
    rawId: 1,
    title: 'Hey Jude',
    year: '1968',
    album: 'Single',
    categoria: 'McCartney',
    duracao: '7:11',
    descricao: 'Single mais vendido dos Beatles (1968), escrito por Paul para acalmar Julian Lennon durante o divórcio dos pais.',
    status: 'Disponível',
    imagem: songsImg,
    compositor: 'Paul McCartney',
    slug: 'hey-jude',
  },
  {
    rawId: 2,
    title: 'Let It Be',
    year: '1970',
    album: 'Let It Be',
    categoria: 'McCartney',
    duracao: '4:03',
    descricao: 'Último single lançado antes da separação oficial. Inspirado em um sonho da mãe de Paul, Mary.',
    status: 'Disponível',
    imagem: songsImg,
    compositor: 'Paul McCartney',
    slug: 'let-it-be',
  },
  {
    rawId: 3,
    title: 'Yesterday',
    year: '1965',
    album: 'Help!',
    categoria: 'McCartney',
    duracao: '2:05',
    descricao: 'Música mais regravada da história da música popular. Paul compôs a melodia em sonho.',
    status: 'Disponível',
    imagem: songsImg,
    compositor: 'Paul McCartney',
    slug: 'yesterday',
  },
  {
    rawId: 5,
    title: 'Come Together',
    year: '1969',
    album: 'Abbey Road',
    categoria: 'Lennon',
    duracao: '4:19',
    descricao: 'Faixa de abertura de Abbey Road. Originalmente escrita para a campanha de Timothy Leary.',
    status: 'Disponível',
    imagem: songsImg,
    compositor: 'John Lennon',
    slug: 'come-together',
  },
  {
    rawId: 6,
    title: 'Something',
    year: '1969',
    album: 'Abbey Road',
    categoria: 'Harrison',
    duracao: '3:02',
    descricao: 'Frank Sinatra chamou de "a melhor canção de amor dos últimos 50 anos".',
    status: 'Disponível',
    imagem: comesSunImg,
    compositor: 'George Harrison',
    slug: 'something',
  },
  {
    rawId: 7,
    title: 'I Want to Hold Your Hand',
    year: '1963',
    album: 'Single',
    categoria: 'Lennon',
    duracao: '2:24',
    descricao: 'Primeiro single dos Beatles a chegar ao topo das paradas americanas.',
    status: 'Disponível',
    imagem: handImg,
    compositor: 'Lennon-McCartney',
    slug: 'i-want-to-hold-your-hand',
  },
  {
    rawId: 8,
    title: 'Eleanor Rigby',
    year: '1966',
    album: 'Revolver',
    categoria: 'Lennon',
    duracao: '2:08',
    descricao: 'Sem instrumentos dos Beatles na gravação — apenas um quarteto de cordas.',
    status: 'Disponível',
    imagem: songsImg,
    compositor: 'Lennon-McCartney',
    slug: 'eleanor-rigby',
  },
  {
    rawId: 9,
    title: 'Blackbird',
    year: '1968',
    album: 'The Beatles (White Album)',
    categoria: 'McCartney',
    duracao: '2:18',
    descricao: 'Solo acústico de Paul em resposta ao movimento dos direitos civis nos EUA.',
    status: 'Disponível',
    imagem: songsImg,
    compositor: 'Paul McCartney',
    slug: 'blackbird',
  },
  {
    rawId: 10,
    title: 'A Day in the Life',
    year: '1967',
    album: "Sgt. Pepper's Lonely Hearts Club Band",
    categoria: 'Lennon',
    duracao: '5:33',
    descricao: 'Faixa de encerramento de Sgt. Pepper. Considerada uma das melhores canções já escritas.',
    status: 'Indisponível',
    imagem: songsImg,
    compositor: 'Lennon-McCartney',
    slug: 'a-day-in-the-life',
  },
]

// Renumera para ids sequenciais 1..N na ordem final (mantém rawId original
// disponível para qualquer código que precise).
export const songs = _songsRaw.map((s, idx) => ({ ...s, id: idx + 1 }))